version: '3'
services:
  sentinel1:
    image: dockerhub.ihome.sxxpqp.top:8443/library/redis:7.4
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel1.conf
    volumes:
      - ./sentinel1:/usr/local/etc/redis
  sentinel2:
    image: dockerhub.ihome.sxxpqp.top:8443/library/redis:7.4
    container_name: redis-sentinel-2
    ports:
    - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel2.conf
    volumes:
      - ./sentinel2:/usr/local/etc/redis
  sentinel3:    
    image: dockerhub.ihome.sxxpqp.top:8443/library/redis:7.4
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel3.conf
    volumes:
      - ./sentinel3:/usr/local/etc/redis
networks:
  default:
    external:
      name: redis_default
