apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.2 # 与原版本一致
imageRepository: dockerhub.ihome.sxxpqp.top:8443/google_containers
controlPlaneEndpoint: "172.16.0.190:6443" # 建议指向负载均衡或新 Master IP
# networking:
#   podSubnet: "10.244.0.0/16" # 必须与旧集群一致
etcd:
  local:
    dataDir: /var/lib/etcd # 确保指向你刚才恢复的 etcd 数据目录
