apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql5.7-deployment
  labels:
    app: mysql5.7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql5.7
  template:
    metadata:
      labels:
        app: mysql5.7
    spec:
      containers:
        - name: mysql5.7
          image: mysql:5.7.44
          ports:
            - containerPort: 3306
              name: mysql-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: mysql-data-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data-volume
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql5.7-service
  labels:
    app: mysql5.7
spec:
  type: NodePort # 可选：ClusterIP（集群内访问）、LoadBalancer（云服务商负载均衡）
  ports:
    - port: 3306
      targetPort: mysql-port
      nodePort: 30066 # 可选，NodePort范围默认30000-32767
  selector:
    app: mysql5.7

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql5.7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # 按需调整存储大小
  # 若使用默认StorageClass，无需指定storageClassName
  # storageClassName: standard
