apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: A4nrIzDZNKFBMBEoelmM
  secretAccessKey: gu6af0CmpW2oF4eQk3wZbCeuOAQ7ir3Av9nnWeJS
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://172.16.0.28:9000
  # If not on S3, set it to ""
  region: ap-east-1
