apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-secret-access
  namespace: gitea
subjects:
  - kind: User
    name: system:node:k8s-master
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access
  namespace: gitea
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
