apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.2
imageRepository: dockerhub.ihome.sxxpqp.top:8443/google_containers
controlPlaneEndpoint: "172.16.0.190:6443"
etcd:
  local:
    dataDir: /var/lib/etcd
apiServer: # <-- 将 'certificates' 修改为 'apiServer'
  certSANs: # <-- 将 'extraSANs' 修改为 'certSANs'
    - 172.16.0.190
    - 172.16.0.191
    - 10.96.0.1
    - 10.96.0.10
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
