version: '3.8'

services:
  rustdesk:
    container_name: rustdesk
    environment:
      ENCRYPTED_ONLY: "1"
      RELAY: "0.0.0.0:21117"
    image: rustdesk/rustdesk-server-s6:latest
    networks:
      - rustdesk
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21117:21117/tcp"
      - "21118:21118/tcp"
      - "21119:21119/tcp"
    restart: always
    volumes:
      - ./rustdesk/data/hbbs:/data
networks:
  rustdesk:
    external: true