version: '3.8'
services:
  frpc:
    image: registry.cn-hangzhou.aliyuncs.com/sxxpqp/frpc
    container_name: frpc
    restart: always
    volumes:
      - /root/frpc/frpc.toml:/frp/frpc.toml
