---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "50000m"
      nginx.ingress.kubernetes.io/client-max-body-size: "50000m"  
    name: dockerhub20250301
    namespace: registry
  spec:
    ingressClassName: nginx
    rules:
    - host: dockerhub20250301.sxxpqp.top
      http:
        paths:
        - backend:
            service:
              name: reg-docker-hub
              port:
                number: 51000
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - dockerhub20250301.sxxpqp.top
      secretName: dockerhub20250301